<!-- Image Map Generated by http://www.image-map.net/ -->
<?php
include_once 'views/blogs/header.php';
?>



<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="assets/img/map1.jpg" style="display: block; margin-left: auto; margin-right: auto; width: 50%;" usemap="#image-map">

<map name="image-map">
    <area target="" alt="North America" title="North America" href="america" coords="78,63,230,207" shape="rect">
    <area target="" alt="South America" title="South America" href="america" coords="138,221,235,323" shape="rect">
    <area target="" alt="Africa" title="Africa" href="" coords="266,176,387,292" shape="rect">
    <area target="" alt="Europe" title="Europe" href="europe" coords="277,78,383,170" shape="rect">
    <area target="" alt="Asia" title="Asia" href="asia" coords="393,82,595,221" shape="rect">
    <area target="" alt="Australia" title="Australia" href="australia" coords="467,231,591,330" shape="rect">
</map>


<?php
include_once 'views/blogs/footer.php';
?>